backend:
  name: github
  repo: Adedoyin-Taiwo/rediserche-website
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "insights"
    label: "Insights"
    folder: "content/insights"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "Use lower-case words separated by hyphens." }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Content Type", name: "insightType", widget: "select", options: ["Thought leadership", "Report", "News", "Case study", "Analysis", "Grant update"] }
      - { label: "Published At", name: "publishedAt", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Category", name: "category", widget: "string", required: false }
      - { label: "Author", name: "author", widget: "string", required: false, default: "RediSerche Team" }
      - { label: "Body", name: "body", widget: "markdown" }
